name: Build
on:
  push:
    branches:
      - "**"
      - "**" 
  pull_request:
    branches:
      - "**"
jobs:
  build:  
    env:
      enable-openapi-integration: ${{ github.repository ==  'Sensedia/draft-openapi' &&  startsWith(github.ref_name,'GT-PR-')}}
    name: Build Github pages 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm install -g widdershins
      - run: npm install -g @apidevtools/swagger-cli

      - name: Compile Swagger Files and generate dictionaries
        run: |
          cd automation-scripts
          bash ./build.sh

      - name: Set Github user data
        id: githubData
        run: |
          echo "::set-output name=git_user_name::$(git --no-pager log --format=format:'%an' -n 1)"
          echo "::set-output name=git_user_email::$(git --no-pager log --format=format:'%ae' -n 1)"
          echo "::set-output name=git_commit_message::$(git --no-pager log --format=format:'%B' -n 1)" 

      - name: Sensedia/openapi Integration
        if: ${{ env.enable-openapi-integration }}
        run: |
          cd automation-scripts
          bash git-repository-integration.sh "${{ steps.githubData.outputs.git_user_email }}"\
           "${{ steps.githubData.outputs.git_user_name }}"\
           "${{ secrets.AREADEV_INTEGRATION }}"\
           "${{ github.ref_name }}"\
           "openapi"\
           "${{ steps.githubData.outputs.git_commit_message }}"

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: 'swagger-apis/**/*.yml'
  deploy:
    env:
       enable-deploy: ${{ github.ref_name == 'tests' || (github.repository !=  'Sensedia/draft-openapi' && github.ref_name == 'main')}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: env.enable-deploy == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
        
